/**
 * Integration tests for the TF-Config JSON export adapter.
 *
 * Tests exportTfConfigJson() against structural assertions on the generated
 * `*.tf.json` output.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { exportTfConfigJson } from "../export-config-json.js";
import type { InfraIR } from "@infrasync/core/schemas";

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Narrow unknown to Record<string, unknown> without type assertion. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Parse JSON string and return as string-keyed object, asserting shape. */
function parseTfJson(raw: string): Record<string, unknown> {
  const parsed: unknown = JSON.parse(raw);
  assert.ok(isRecord(parsed), "Expected parsed JSON to be a plain object");
  return parsed;
}

/** Assert value is a string-keyed record and return it. */
function obj(value: unknown, label: string): Record<string, unknown> {
  assert.ok(isRecord(value), `Expected ${label} to be a plain object`);
  return value;
}

const emptyIr: InfraIR = {
  name: "test",
  providers: [],
  resources: [],
};

const singleProviderIr: InfraIR = {
  name: "test",
  providers: [
    {
      key: "cf",
      adapterName: "cloudflare",
      config: {
        apiToken: { $secret: { kind: "env", name: "CF_API_TOKEN" } },
      },
    },
  ],
  resources: [],
};

// ─── Empty IR ────────────────────────────────────────────────────────────────

test("empty IR produces valid tf.json with comment", () => {
  const result = exportTfConfigJson(emptyIr);
  const tf = parseTfJson(result.content);

  assert.equal(tf["//"], 'Generated by InfraSync from "test". Do not edit.');
  assert.ok(tf.terraform !== undefined);
  assert.deepEqual(
    obj(obj(tf.terraform, "terraform").required_providers, "rp"),
    {},
  );
  assert.equal(tf.resource, undefined);
  assert.equal(tf.data, undefined);
  assert.equal(result.fidelity.issues.length, 0);
});

// ─── Provider blocks ─────────────────────────────────────────────────────────

test("single provider with secret config produces terraform block and variable", () => {
  const result = exportTfConfigJson(singleProviderIr);
  const tf = parseTfJson(result.content);

  const terraform = obj(tf.terraform, "terraform");
  const requiredProviders = obj(terraform.required_providers, "rp");
  const cfEntry = obj(requiredProviders.cloudflare, "cloudflare");
  assert.equal(cfEntry.source, "cloudflare/cloudflare");

  // Provider block with variable reference for secret
  const provider = obj(tf.provider, "provider");
  const cfProvider = obj(provider.cloudflare, "cloudflare provider");
  assert.equal(cfProvider.apiToken, "${var.CF_API_TOKEN}");

  // Variable block
  const variable = obj(tf.variable, "variable");
  const cfToken = obj(variable.CF_API_TOKEN, "CF_API_TOKEN var");
  assert.equal(cfToken.type, "string");
  assert.equal(cfToken.sensitive, true);
});

test("unknown adapter name without override throws", () => {
  const ir: InfraIR = {
    name: "test",
    providers: [{ key: "custom", adapterName: "my-custom", config: {} }],
    resources: [],
  };

  assert.throws(
    () => exportTfConfigJson(ir),
    /No Terraform provider source mapping for provider instance/,
  );
});

test("custom provider source override works", () => {
  const ir: InfraIR = {
    name: "test",
    providers: [{ key: "custom", adapterName: "my-custom", config: {} }],
    resources: [],
  };

  const result = exportTfConfigJson(ir, {
    providerSources: { "my-custom": "acme/my-custom" },
  });
  const tf = parseTfJson(result.content);

  const terraform = obj(tf.terraform, "terraform");
  const rp = obj(terraform.required_providers, "rp");
  const entry = obj(rp["my-custom"], "my-custom entry");
  assert.equal(entry.source, "acme/my-custom");
});

// ─── Resource blocks ─────────────────────────────────────────────────────────

test("managed resource produces resource block", () => {
  const result = exportTfConfigJson({
    name: "test",
    providers: [{ key: "cf", adapterName: "cloudflare", config: {} }],
    resources: [
      {
        name: "wwwRecord",
        provider: "cf",
        kind: "DnsRecord",
        mode: "manage",
        spec: {
          zoneId: "abc123",
          type: "CNAME",
          content: "target.example.com",
        },
      },
    ],
  });

  const tf = parseTfJson(result.content);
  const resource = obj(tf.resource, "resource");
  const cfType = obj(resource.cloudflare_dns_record, "dns record type");
  const record = obj(cfType.www_record, "www_record");
  assert.equal(record.zoneId, "abc123");
  assert.equal(record.type, "CNAME");
  assert.equal(record.content, "target.example.com");
});

test("read-mode resource produces data block", () => {
  const result = exportTfConfigJson({
    name: "test",
    providers: [{ key: "aws", adapterName: "aws", config: {} }],
    resources: [
      {
        name: "ubuntuAmi",
        provider: "aws",
        kind: "Ami",
        mode: "read",
        spec: { name: "ubuntu-22.04" },
      },
    ],
  });

  const tf = parseTfJson(result.content);
  const data = obj(tf.data, "data");
  const awsAmi = obj(data.aws_ami, "aws_ami");
  const ami = obj(awsAmi.ubuntu_ami, "ubuntu_ami");
  assert.equal(ami.name, "ubuntu-22.04");
  assert.equal(tf.resource, undefined);
});

// ─── Depends on ──────────────────────────────────────────────────────────────

test("dependsOn produces depends_on meta-argument", () => {
  const result = exportTfConfigJson({
    name: "test",
    providers: [{ key: "cf", adapterName: "cloudflare", config: {} }],
    resources: [
      {
        name: "zone",
        provider: "cf",
        kind: "Zone",
        mode: "manage",
        spec: { domain: "example.com" },
      },
      {
        name: "record",
        provider: "cf",
        kind: "DnsRecord",
        mode: "manage",
        spec: { zoneId: "abc", type: "A", content: "1.2.3.4" },
        dependsOn: ["zone"],
      },
    ],
  });

  const tf = parseTfJson(result.content);
  const resource = obj(tf.resource, "resource");
  const dnsType = obj(resource.cloudflare_dns_record, "dns type");
  const record = obj(dnsType.record, "record");
  assert.deepEqual(record.depends_on, ["cloudflare_zone.zone"]);
});

// ─── Ref tokens ──────────────────────────────────────────────────────────────

test("RefToken in spec resolves to Terraform expression string", () => {
  const result = exportTfConfigJson({
    name: "test",
    providers: [{ key: "cf", adapterName: "cloudflare", config: {} }],
    resources: [
      {
        name: "zone",
        provider: "cf",
        kind: "Zone",
        mode: "manage",
        spec: { domain: "example.com" },
      },
      {
        name: "record",
        provider: "cf",
        kind: "DnsRecord",
        mode: "manage",
        spec: {
          zoneId: {
            $ref: { resource: "zone", path: "zoneId" },
          },
          type: "CNAME",
          content: "target.example.com",
        },
      },
    ],
  });

  const tf = parseTfJson(result.content);
  const resource = obj(tf.resource, "resource");
  const dnsType = obj(resource.cloudflare_dns_record, "dns type");
  const record = obj(dnsType.record, "record");
  assert.equal(record.zoneId, "${cloudflare_zone.zone.zoneId}");
});

// ─── Multiple provider instances (aliases) ───────────────────────────────────

test("multiple instances of same adapter produce provider aliases", () => {
  const result = exportTfConfigJson({
    name: "test",
    providers: [
      {
        key: "awsProd",
        adapterName: "aws",
        config: { region: "eu-west-1" },
      },
      {
        key: "awsStaging",
        adapterName: "aws",
        config: { region: "us-east-1" },
      },
    ],
    resources: [
      {
        name: "prodBucket",
        provider: "awsProd",
        kind: "S3Bucket",
        mode: "manage",
        spec: { bucket: "prod-bucket" },
      },
      {
        name: "stagingBucket",
        provider: "awsStaging",
        kind: "S3Bucket",
        mode: "manage",
        spec: { bucket: "staging-bucket" },
      },
    ],
  });

  const tf = parseTfJson(result.content);
  const resource = obj(tf.resource, "resource");
  const s3Type = obj(resource.aws_s3_bucket, "s3 type");
  const prod = obj(s3Type.prod_bucket, "prod_bucket");
  const staging = obj(s3Type.staging_bucket, "staging_bucket");

  assert.equal(prod.provider, "aws.aws_prod");
  assert.equal(staging.provider, "aws.aws_staging");
});

// ─── Error cases ─────────────────────────────────────────────────────────────

test("resource referencing unknown provider throws", () => {
  assert.throws(
    () =>
      exportTfConfigJson({
        name: "test",
        providers: [],
        resources: [
          {
            name: "orphan",
            provider: "nonexistent",
            kind: "Thing",
            mode: "manage",
            spec: {},
          },
        ],
      }),
    /references unknown provider instance/,
  );
});

test("duplicate resource names produce last-wins (Terraform semantics)", () => {
  // Terraform JSON itself is last-wins for duplicate keys within a block type,
  // but JSON.stringify deduplicates object keys. We accept this as fidelity loss.
  const result = exportTfConfigJson({
    name: "test",
    providers: [{ key: "cf", adapterName: "cloudflare", config: {} }],
    resources: [
      {
        name: "thing",
        provider: "cf",
        kind: "DnsRecord",
        mode: "manage",
        spec: { type: "A", content: "1.1.1.1" },
      },
      {
        name: "thing",
        provider: "cf",
        kind: "DnsRecord",
        mode: "manage",
        spec: { type: "CNAME", content: "target.com" },
      },
    ],
  });

  // Both resources map to same type+name — last one wins in JSON object keys
  const tf = parseTfJson(result.content);
  const resource = obj(tf.resource, "resource");
  const dnsType = obj(resource.cloudflare_dns_record, "dns type");
  const record = obj(dnsType.thing, "thing");
  assert.equal(record.type, "CNAME");
});
