/**
 * Integration tests for the TF-Config JSON import adapter.
 *
 * Tests importTfConfigJson() against structural assertions on the
 * resulting InfraIR document.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  importTfConfigJson,
  type TfConfigJsonImportResult,
} from "../import-config-json.js";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function assertResource(
  result: TfConfigJsonImportResult,
  name: string,
): Record<string, unknown> {
  const resource = result.ir.resources.find((r) => r.name === name);
  assert.ok(resource !== undefined, `Resource "${name}" not found`);
  assert.ok(isRecord(resource.spec), `Resource "${name}" spec is not a record`);
  return resource.spec;
}

function findResource(result: TfConfigJsonImportResult, name: string) {
  const resource = result.ir.resources.find((r) => r.name === name);
  assert.ok(resource !== undefined, `Resource "${name}" not found`);
  return resource;
}

function firstProvider(result: TfConfigJsonImportResult) {
  assert.ok(result.ir.providers.length > 0, "Expected at least one provider");
  // eslint autofix may have collapsed the function signature
  const provider = result.ir.providers[0];
  assert.ok(provider !== undefined);
  return provider;
}

// ─── Minimal valid tf.json ───────────────────────────────────────────────────

test("empty tf.json produces empty IR", () => {
  const result = importTfConfigJson("{}");
  assert.equal(result.ir.name, "imported");
  assert.equal(result.ir.providers.length, 0);
  assert.equal(result.ir.resources.length, 0);
  assert.equal(result.fidelity.issues.length, 0);
});

test("name extracted from comment property", () => {
  const result = importTfConfigJson(
    JSON.stringify({
      "//": 'Generated by InfraSync from "my-stack". Do not edit.',
    }),
  );
  assert.equal(result.ir.name, "my-stack");
});

test("custom name overrides comment extraction", () => {
  const result = importTfConfigJson("{}", { name: "custom" });
  assert.equal(result.ir.name, "custom");
});

// ─── Provider blocks ─────────────────────────────────────────────────────────

test("required_providers produces provider instances", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        cloudflare: { source: "cloudflare/cloudflare" },
      },
    },
  });

  const result = importTfConfigJson(tfJson);
  assert.equal(result.ir.providers.length, 1);
  const provider = firstProvider(result);
  assert.equal(provider.adapterName, "cloudflare");
  assert.equal(provider.key, "Cloudflare");
});

test("provider block with config values", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        aws: { source: "hashicorp/aws" },
      },
    },
    provider: {
      aws: { region: "eu-west-1" },
    },
  });

  const result = importTfConfigJson(tfJson);
  const provider = firstProvider(result);
  assert.equal(provider.config.region, "eu-west-1");
});

test("provider with variable reference converts to SecretSourceIR", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        cloudflare: { source: "cloudflare/cloudflare" },
      },
    },
    provider: {
      cloudflare: { api_token: "${var.CF_API_TOKEN}" },
    },
  });

  const result = importTfConfigJson(tfJson);
  const config = firstProvider(result).config;
  assert.ok(isRecord(config.api_token));
  assert.ok("$secret" in config.api_token);
});

// ─── Resource blocks ─────────────────────────────────────────────────────────

test("resource blocks produce managed resources", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        cloudflare: { source: "cloudflare/cloudflare" },
      },
    },
    resource: {
      cloudflare_record: {
        www: {
          zone_id: "abc123",
          type: "CNAME",
          content: "target.example.com",
        },
      },
    },
  });

  const result = importTfConfigJson(tfJson);
  assert.equal(result.ir.resources.length, 1);

  const resource = findResource(result, "www");
  assert.equal(resource.kind, "Record");
  assert.equal(resource.mode, "manage");
  assert.equal(resource.provider, "Cloudflare");
  assert.equal(resource.spec.zone_id, "abc123");
});

test("data blocks produce read-mode resources", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        aws: { source: "hashicorp/aws" },
      },
    },
    data: {
      aws_ami: {
        ubuntu: { name: "ubuntu-22.04" },
      },
    },
  });

  const result = importTfConfigJson(tfJson);
  assert.equal(result.ir.resources.length, 1);

  const resource = findResource(result, "ubuntu");
  assert.equal(resource.mode, "read");
  assert.equal(resource.kind, "Ami");
  assert.equal(resource.name, "ubuntu");
});

// ─── depends_on ──────────────────────────────────────────────────────────────

test("depends_on produces dependsOn array", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        cloudflare: { source: "cloudflare/cloudflare" },
      },
    },
    resource: {
      cloudflare_zone: {
        main: { domain: "example.com" },
      },
      cloudflare_record: {
        www: {
          zone_id: "abc",
          type: "A",
          content: "1.2.3.4",
          depends_on: ["cloudflare_zone.main"],
        },
      },
    },
  });

  const result = importTfConfigJson(tfJson);
  const record = findResource(result, "www");
  assert.deepEqual(record.dependsOn, ["main"]);
});

// ─── Ref tokens ──────────────────────────────────────────────────────────────

test("resource reference expression converts to RefTokenIR", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        cloudflare: { source: "cloudflare/cloudflare" },
      },
    },
    resource: {
      cloudflare_zone: {
        main: { domain: "example.com" },
      },
      cloudflare_record: {
        www: {
          zone_id: "${cloudflare_zone.main.zone_id}",
          type: "CNAME",
          content: "target.example.com",
        },
      },
    },
  });

  const result = importTfConfigJson(tfJson);
  const spec = assertResource(result, "www");

  assert.ok(isRecord(spec.zone_id));
  assert.ok("$ref" in spec.zone_id);

  const ref = spec.zone_id;
  if (isRecord(ref) && isRecord(ref.$ref)) {
    assert.equal(ref.$ref.resource, "main");
    assert.equal(ref.$ref.path, "zone_id");
  }
});

// ─── Meta-arguments dropped ──────────────────────────────────────────────────

test("lifecycle meta-argument is dropped with fidelity warning", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        aws: { source: "hashicorp/aws" },
      },
    },
    resource: {
      aws_s3_bucket: {
        data: {
          bucket: "data-bucket",
          lifecycle: { ignore_changes: ["tags"] },
        },
      },
    },
  });

  const result = importTfConfigJson(tfJson);
  const spec = assertResource(result, "data");
  assert.equal(spec.lifecycle, undefined);

  const lifecycleIssues = result.fidelity.issues.filter((i) =>
    i.path.includes("lifecycle"),
  );
  assert.ok(lifecycleIssues.length > 0);
});

test("provider meta-argument maps to provider instance key", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        aws: { source: "hashicorp/aws" },
      },
    },
    resource: {
      aws_s3_bucket: {
        data: {
          bucket: "data-bucket",
          provider: "aws.prod",
        },
      },
    },
  });

  const result = importTfConfigJson(tfJson);
  const resource = findResource(result, "data");
  assert.equal(resource.provider, "Prod");
  assert.equal(resource.spec.provider, undefined);
});

// ─── Unsupported blocks ──────────────────────────────────────────────────────

test("locals block reports unsupported fidelity issue", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        aws: { source: "hashicorp/aws" },
      },
    },
    locals: { my_local: "value" },
  });

  const result = importTfConfigJson(tfJson);
  const localIssues = result.fidelity.issues.filter((i) =>
    i.path.includes("locals"),
  );
  assert.ok(localIssues.length > 0);
  const firstIssue = localIssues[0];
  assert.ok(firstIssue !== undefined);
  assert.equal(firstIssue.class, "unsupported");
});

test("module block reports unsupported fidelity issue", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        aws: { source: "hashicorp/aws" },
      },
    },
    module: { vpc: { source: "terraform-aws-modules/vpc/aws" } },
  });

  const result = importTfConfigJson(tfJson);
  const moduleIssues = result.fidelity.issues.filter((i) =>
    i.path.includes("module"),
  );
  assert.ok(moduleIssues.length > 0);
});

test("output block reports unsupported fidelity issue", () => {
  const tfJson = JSON.stringify({
    terraform: {
      required_providers: {
        aws: { source: "hashicorp/aws" },
      },
    },
    output: { bucket_arn: { value: "${aws_s3_bucket.data.arn}" } },
  });

  const result = importTfConfigJson(tfJson);
  const outputIssues = result.fidelity.issues.filter((i) =>
    i.path.includes("output"),
  );
  assert.ok(outputIssues.length > 0);
});

// ─── Round-trip fixture ──────────────────────────────────────────────────────

test("exported then re-imported IR preserves core structure", () => {
  // Build a tf.json that matches what the exporter would produce
  const tfJson = JSON.stringify({
    "//": 'Generated by InfraSync from "round-trip-test". Do not edit.',
    terraform: {
      required_providers: {
        cloudflare: { source: "cloudflare/cloudflare" },
      },
    },
    provider: {
      cloudflare: { api_token: "${var.CF_TOKEN}" },
    },
    resource: {
      cloudflare_zone: {
        main: { domain: "example.com" },
      },
      cloudflare_record: {
        www: {
          zone_id: "${cloudflare_zone.main.id}",
          type: "CNAME",
          content: "target.example.com",
          depends_on: ["cloudflare_zone.main"],
        },
      },
    },
    variable: {
      CF_TOKEN: { type: "string", sensitive: true },
    },
  });

  const result = importTfConfigJson(tfJson);

  // Name preserved from comment
  assert.equal(result.ir.name, "round-trip-test");

  // Provider preserved
  assert.equal(result.ir.providers.length, 1);
  const provider = firstProvider(result);
  assert.equal(provider.adapterName, "cloudflare");

  // Resources preserved
  assert.equal(result.ir.resources.length, 2);

  const zone = findResource(result, "main");
  assert.equal(zone.kind, "Zone");
  assert.equal(zone.mode, "manage");
  assert.equal(zone.spec.domain, "example.com");

  const record = findResource(result, "www");
  assert.equal(record.kind, "Record");
  assert.deepEqual(record.dependsOn, ["main"]);

  // Ref token preserved
  const zoneIdSpec = record.spec.zone_id;
  assert.ok(isRecord(zoneIdSpec));
  assert.ok("$ref" in zoneIdSpec);
});

// ─── Error cases ─────────────────────────────────────────────────────────────

test("non-object JSON throws", () => {
  assert.throws(() => importTfConfigJson("[]"), /root must be a JSON object/);
});

test("invalid JSON throws", () => {
  assert.throws(() => importTfConfigJson("{invalid}"));
});
