/**
 * Adapter for exporting InfraIR to Terraform Configuration JSON (`*.tf.json`).
 *
 * This is the **execution lane** — produces Terraform-applyable configuration.
 *
 * Mapping rules:
 * - InfraIR.providers → `terraform.required_providers` + `provider` blocks
 * - InfraIR.resources with mode "manage" → `resource` blocks
 * - InfraIR.resources with mode "read" → `data` blocks
 * - RefTokenIR → Terraform expression strings (`${type.name.path}`)
 * - SecretSourceIR → Terraform variable references (`var.name`)
 * - dependsOn → `depends_on` meta-argument
 *
 * Provider source mapping requires a registry mapping adapter names to
 * Terraform provider source strings (e.g. "cloudflare" → "cloudflare/cloudflare").
 */
import { FidelityReportBuilder } from "@infrasync/core-fidelity/fidelity";
import type { AdapterResult } from "@infrasync/core-fidelity/fidelity";
import type { InfraIR, RefTokenIR } from "@infrasync/core/schemas";

// ─── Provider source registry ────────────────────────────────────────────────

/** Default adapter → Terraform provider source mappings. */
const DEFAULT_PROVIDER_SOURCES: Readonly<Record<string, string>> = {
  cloudflare: "cloudflare/cloudflare",
  aws: "hashicorp/aws",
  gcp: "hashicorp/google",
  github: "integrations/github",
  vercel: "vercel/vercel",
  google: "hashicorp/google",
  azurerm: "hashicorp/azurerm",
};

// ─── Export options ───────────────────────────────────────────────────────────

/** Maps an InfraSync resource kind to a Terraform resource type and spec transform. */
export interface ResourceMapper {
  /** InfraSync resource kind (e.g. "DnsRecord") */
  readonly kind: string;
  /** Terraform resource type (e.g. "cloudflare_record") */
  readonly tfType: string;
  /** Transform spec fields to Terraform attribute names. */
  readonly mapSpec?:
    | ((spec: Readonly<Record<string, unknown>>) => Record<string, unknown>)
    | undefined;
}

export interface TfConfigJsonExportOptions {
  /** Override provider source mappings (adapter name → registry source). */
  readonly providerSources?: Readonly<Record<string, string>> | undefined;
  /** Per-adapter resource mappers (adapter name → mappers). */
  readonly resourceMappers?:
    | Readonly<Record<string, readonly ResourceMapper[]>>
    | undefined;
}

// ─── Export result ────────────────────────────────────────────────────────────

export interface TfConfigJsonExportResult {
  /** The generated `*.tf.json` content as a string. */
  readonly content: string;
  readonly fidelity: AdapterResult<unknown>["fidelity"];
  readonly warnings: readonly string[];
}

// ─── Type guard helpers ───────────────────────────────────────────────────────

/** Narrow unknown to Record<string, unknown> without type assertion. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isRefToken(value: unknown): value is RefTokenIR {
  if (!isRecord(value)) return false;
  if (!("$ref" in value)) return false;
  const ref = value.$ref;
  return typeof ref === "object" && ref !== null;
}

interface SecretSourceLike {
  readonly $secret: { readonly kind: string; readonly name: string };
}

function isSecretSource(value: unknown): value is SecretSourceLike {
  if (!isRecord(value)) return false;
  if (!("$secret" in value)) return false;
  const secret = value.$secret;
  return typeof secret === "object" && secret !== null;
}

// ─── Export function ──────────────────────────────────────────────────────────

/**
 * Export an InfraIR document as Terraform Configuration JSON.
 *
 * Produces a single `*.tf.json` file that can be applied with `terraform apply`.
 *
 * @throws Error if a provider has no source mapping and no override is provided.
 * @throws Error on references to unknown providers or resources.
 */
export function exportTfConfigJson(
  ir: InfraIR,
  options: TfConfigJsonExportOptions = {},
): TfConfigJsonExportResult {
  const reporter = new FidelityReportBuilder();
  const providerSources = resolveProviderSources(
    ir.providers,
    options.providerSources,
    reporter,
  );

  const tfConfig: Record<string, unknown> = {
    "//": `Generated by InfraSync from "${ir.name}". Do not edit.`,
  };

  // ── terraform block ──────────────────────────────────────────────────────

  const requiredProviders: Record<
    string,
    { source: string; version?: string }
  > = {};
  const providerBlocks: Record<string, Record<string, unknown>> = {};

  for (const provider of ir.providers) {
    const source = providerSources.get(provider.key);
    if (source === undefined) {
      throw new Error(
        `No Terraform provider source mapping for provider instance "${provider.key}" (adapter: "${provider.adapterName}")`,
      );
    }

    requiredProviders[provider.adapterName] = { source };

    // Provider config — resolve secrets to variable references
    const providerConfig = resolveProviderConfig(provider.config, reporter);
    if (Object.keys(providerConfig).length > 0) {
      providerBlocks[provider.adapterName] = providerConfig;
    }
  }

  tfConfig.terraform = { required_providers: requiredProviders };
  if (Object.keys(providerBlocks).length > 0) {
    tfConfig.provider = providerBlocks;
  }

  // ── resource and data blocks ─────────────────────────────────────────────

  const resourceBlocks: Record<
    string,
    Record<string, Record<string, unknown>>
  > = {};
  const dataBlocks: Record<
    string,
    Record<string, Record<string, unknown>>
  > = {};

  const providerInstanceToAdapter = new Map<string, string>();
  for (const provider of ir.providers) {
    providerInstanceToAdapter.set(provider.key, provider.adapterName);
  }

  // Track resource addresses for ref resolution
  const resourceAddresses = new Map<string, { type: string; name: string }>();

  for (const resource of ir.resources) {
    const adapterName = providerInstanceToAdapter.get(resource.provider);
    if (adapterName === undefined) {
      throw new Error(
        `Resource "${resource.name}" references unknown provider instance "${resource.provider}"`,
      );
    }

    // Convert InfraSync resource kind to Terraform resource type.
    // First check for explicit mapper, then fall back to convention.
    const mapper = options.resourceMappers?.[adapterName]?.find(
      (m) => m.kind === resource.kind,
    );
    const tfType =
      mapper?.tfType ?? `${adapterName}_${toSnakeCase(resource.kind)}`;
    const tfName = toSnakeCase(resource.name);

    // Track for ref resolution
    resourceAddresses.set(resource.name, { type: tfType, name: tfName });

    // Resolve spec values — translate RefTokens to Terraform expressions
    const rawSpec =
      mapper?.mapSpec !== undefined
        ? mapper.mapSpec(resource.spec)
        : resource.spec;
    const resolvedSpec = resolveSpecValues(
      rawSpec,
      resourceAddresses,
      reporter,
    );

    // Add depends_on if present
    const dependsOn = resource.dependsOn;
    if (dependsOn !== undefined && dependsOn.length > 0) {
      const resolvedDeps: string[] = [];
      for (const depName of dependsOn) {
        const dep = resourceAddresses.get(depName);
        if (dep === undefined) {
          throw new Error(
            `Resource "${resource.name}" depends on unknown resource "${depName}"`,
          );
        }
        resolvedDeps.push(`${dep.type}.${dep.name}`);
      }
      resolvedSpec.depends_on = resolvedDeps;
    }

    // Add provider alias if needed (multiple instances of same adapter)
    const sameAdapterInstances = ir.providers.filter(
      (p) => p.adapterName === adapterName,
    );
    if (sameAdapterInstances.length > 1) {
      resolvedSpec.provider = `${adapterName}.${toSnakeCase(resource.provider)}`;
    }

    const blocks = resource.mode === "read" ? dataBlocks : resourceBlocks;
    blocks[tfType] ??= {};
    blocks[tfType][tfName] = resolvedSpec;
  }

  if (Object.keys(resourceBlocks).length > 0) {
    tfConfig.resource = resourceBlocks;
  }
  if (Object.keys(dataBlocks).length > 0) {
    tfConfig.data = dataBlocks;
  }

  // ── variable blocks for secrets ──────────────────────────────────────────

  const variableBlocks = collectVariables(ir);
  if (Object.keys(variableBlocks).length > 0) {
    tfConfig.variable = variableBlocks;
  }

  const result = reporter.result(tfConfig);

  return {
    content: JSON.stringify(result.document, null, 2) + "\n",
    fidelity: result.fidelity,
    warnings: result.warnings,
  };
}

// ─── Provider source resolution ───────────────────────────────────────────────

function resolveProviderSources(
  providers: readonly { readonly key: string; readonly adapterName: string }[],
  overrides: Readonly<Record<string, string>> | undefined,
  reporter: FidelityReportBuilder,
): Map<string, string> {
  const sources = new Map<string, string>();

  for (const provider of providers) {
    const override =
      overrides !== undefined ? overrides[provider.adapterName] : undefined;
    const source = override ?? DEFAULT_PROVIDER_SOURCES[provider.adapterName];

    if (source === undefined) {
      reporter.addIssue({
        path: `provider.${provider.key}`,
        class: "unsupported",
        message: `No Terraform provider source mapping for adapter "${provider.adapterName}"`,
        action: "dropped",
      });
      continue;
    }

    if (override !== undefined) {
      reporter.addIssue({
        path: `provider.${provider.key}`,
        class: "lossy",
        message: `Provider source overridden from "${DEFAULT_PROVIDER_SOURCES[provider.adapterName] ?? "unknown"}" to "${source}"`,
        action: "approximated",
      });
    }

    sources.set(provider.key, source);
  }

  return sources;
}

// ─── Spec value resolution ────────────────────────────────────────────────────

function resolveSpecValues(
  spec: Readonly<Record<string, unknown>>,
  resourceAddresses: Map<string, { type: string; name: string }>,
  reporter: FidelityReportBuilder,
): Record<string, unknown> {
  const resolved: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(spec)) {
    resolved[key] = resolveValue(value, key, resourceAddresses, reporter);
  }

  return resolved;
}

function resolveValue(
  value: unknown,
  path: string,
  resourceAddresses: Map<string, { type: string; name: string }>,
  reporter: FidelityReportBuilder,
): unknown {
  if (isRefToken(value)) {
    return resolveRefToken(value, path, resourceAddresses, reporter);
  }

  if (isSecretSource(value)) {
    return `\${var.${value.$secret.name}}`;
  }

  if (Array.isArray(value)) {
    return value.map((item, i) =>
      resolveValue(item, `${path}[${String(i)}]`, resourceAddresses, reporter),
    );
  }

  if (isRecord(value)) {
    return resolveSpecValues(value, resourceAddresses, reporter);
  }

  return value;
}

function resolveRefToken(
  token: RefTokenIR,
  path: string,
  resourceAddresses: Map<string, { type: string; name: string }>,
  reporter: FidelityReportBuilder,
): string {
  const target = resourceAddresses.get(token.$ref.resource);
  if (target === undefined) {
    reporter.addIssue({
      path,
      class: "lossy",
      message: `RefToken target "${token.$ref.resource}" has no corresponding Terraform resource address`,
      action: "approximated",
    });
    // Fall back to the raw reference string
    return `\${${token.$ref.resource}.${token.$ref.path}}`;
  }
  return `\${${target.type}.${target.name}.${token.$ref.path}}`;
}

// ─── Provider config resolution ───────────────────────────────────────────────

function resolveProviderConfig(
  config: Readonly<Record<string, unknown>>,
  reporter: FidelityReportBuilder,
): Record<string, unknown> {
  const resolved: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(config)) {
    if (isSecretSource(value)) {
      // Map secrets to Terraform variable references
      resolved[key] = `\${var.${value.$secret.name}}`;
    } else if (isRefToken(value)) {
      reporter.addIssue({
        path: `provider_config.${key}`,
        class: "unsupported",
        message:
          "RefToken in provider config cannot be expressed in Terraform JSON config",
        action: "dropped",
      });
    } else {
      resolved[key] = value;
    }
  }

  return resolved;
}

// ─── Variable collection ─────────────────────────────────────────────────────

function collectVariables(
  ir: InfraIR,
): Record<string, Record<string, unknown>> {
  const variables: Record<string, Record<string, unknown>> = {};

  // Collect from provider configs
  for (const provider of ir.providers) {
    for (const value of Object.values(provider.config)) {
      if (isSecretSource(value)) {
        const varName = value.$secret.name;
        variables[varName] ??= {
          type: "string",
          sensitive: true,
        };
      }
    }
  }

  return variables;
}

// ─── Case conversion ──────────────────────────────────────────────────────────

function toSnakeCase(input: string): string {
  return input
    .replace(/([A-Z])/g, "_$1")
    .replace(/^_/, "")
    .toLowerCase();
}
